const tiposDeError = {
  ERROR_ARGUMENTOS_INVALIDOS: 400,
  ERROR_DATOS: 400,
  ERROR_ID_CARRITO: 401,
  STOCK_INSUFICIENTE: 400,
  ERROR_AUTENTICACION: 401,
  ERROR_AUTORIZACION: 403,
  ERROR_RECURSO_NO_ENCONTRADO: 404,
  ERROR_INTERNO_SERVIDOR: 500,
  PRODUCTO_NO_ENCONTRADO: 404,
  USUARIO_NO_ENCONTRADO: 404,
  CARRITO_NO_ENCONTRADO: 404,
  ERROR_CREAR_PRODUCTO: 500,
  ERROR_OBTENER_PRODUCTO: 500,
  ERROR_ACTUALIZAR_PRODUCTO: 500,
  ERROR_ELIMINAR_PRODUCTO: 500,
  CODIGO_DUPLICADO: 400,
  ERROR_CREAR_USUARIO: 500,
  ERROR_OBTENER_USUARIO: 500,
  ERROR_ACTUALIZAR_USUARIO: 500,
  USUARIO_NO_ENCONTRADO: 404,
  ERROR_ELIMINAR_USUARIO: 500,
};

module.exports = tiposDeError;
/*
const tiposDeError = {
  ERROR_ARGUMENTOS_INVALIDOS: 400,
  ERROR_DATOS: 400,
  STOCK_INSUFICIENTE: 400,
  ERROR_AUTENTICACION: 401,
  ERROR_AUTORIZACION: 403,
  ERROR_RECURSO_NO_ENCONTRADO: 404,
  ERROR_INTERNO_SERVIDOR: 500,
  PRODUCTO_NO_ENCONTRADO: 404,
  ERROR_CREAR_USUARIO: 500, 
  ERROR_OBTENER_USUARIO: 500, 
  ERROR_OBTENER_USUARIOS: 500, 
  ERROR_ACTUALIZAR_USUARIO: 500, 
  USUARIO_NO_ENCONTRADO: 404, 
  ERROR_ELIMINAR_USUARIO: 500, 
};

module.exports = tiposDeError;

*/
